# STAGE 1
FROM golang:1.25-alpine AS build-stage

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/golang-app ./


# STAGE 2

FROM scratch

WORKDIR /app

COPY --from=build-stage /usr/local/bin/golang-app ./

EXPOSE 8000

ENTRYPOINT ["/app/golang-app"]